import { IconNames } from "../../components/Icon/IconNames";
import STRINGS from "../strings";

// eslint-disable-next-line import/prefer-default-export
export const buttonActions = [
  {
    index: 0,
    popOver: false,
    notificationNumber: 0,
    iconName: "rx" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
    toolTipTitle: STRINGS.buttonGrid.RX_REQUESTS,
  },
  {
    index: 1,
    popOver: false,
    notificationNumber: 0,
    iconName: "lab" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
    toolTipTitle: STRINGS.buttonGrid.LAB_REQUESTS,
  },
  {
    index: 2,
    popOver: false,
    notificationNumber: 0,
    iconName: "pharmacy" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
    toolTipTitle: STRINGS.buttonGrid.RECIPES,
  },
  {
    index: 3,
    popOver: true,
    notificationNumber: 0,
    iconName: "twoUser" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
    toolTipTitle: STRINGS.buttonGrid.INTER_CONSULT,
    popOverAction: {
      firstAction: STRINGS.buttonGrid.NEW_INTER_CONSULT,
      secondAction: STRINGS.buttonGrid.HISTORICAL_INTER_CONSULT,
    },
  },
  {
    index: 5,
    popOver: false,
    notificationNumber: 0,
    iconName: "leftSheet" as IconNames,
    toolTipTitle: STRINGS.buttonGrid.RESULTS,
    iconHeight: 18,
    iconWidth: 18,
  },
  {
    index: 6,
    popOver: false,
    notificationNumber: 0,
    iconName: "shield" as IconNames,
    toolTipTitle: STRINGS.buttonGrid.INSURANCES,
    iconHeight: 18,
    iconWidth: 18,
  },
  {
    index: 4,
    popOver: false,
    notificationNumber: 0,
    iconName: "edit" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
    toolTipTitle: STRINGS.generals.EDIT,
  },
  {
    index: 7,
    popOver: true,
    notificationNumber: 0,
    iconName: "form" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
    toolTipTitle: STRINGS.buttonGrid.CERTIFICATE,
    popOverAction: {
      firstAction: STRINGS.certificates.NEW_CERTIFICATE,
      secondAction: STRINGS.certificates.CERTIFICATE_HISTORY,
    },
  },
  {
    index: 8,
    popOver: false,
    notificationNumber: 0,
    toolTipTitle: STRINGS.buttonGrid.FILES,
    iconName: "folder" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
  },
  {
    index: 9,
    popOver: false,
    notificationNumber: 0,
    iconName: "rigthSheet" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
    toolTipTitle: STRINGS.buttonGrid.INFORM_CONSENTS,
  },
  {
    index: 10,
    popOver: true,
    notificationNumber: 0,
    iconName: "squaredrBox" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
    toolTipTitle: STRINGS.procedure.PROCEDURE,
    popOverAction: {
      firstAction: STRINGS.procedure.NEW_PROCEDURE,
      secondAction: STRINGS.procedure.PROCEDURE_HISTORY,
    },
  },
  {
    index: 11,
    popOver: true,
    notificationNumber: 0,
    iconName: "checkList" as IconNames,
    iconHeight: 18,
    iconWidth: 18,
    toolTipTitle: STRINGS.generals.INFORMS,
    popOverAction: {
      firstAction: STRINGS.reports.NEW_REPORT,
      secondAction: STRINGS.reports.REPORTS_HISTORY,
    },
  },
];
