const STRINGS = {
  generals: {
    BEGIN: "Iniciar",
    HELLO: "Hola",
    IMAGE: "Imagen",
    PUBLIC_PROFILE: "Perfil Público",
    ADJUST_ACCOUNT: "Ajustes de Cuenta",
    FAQS: "FAQs",
    END_SESSION: "Cerrar sesión",
    NEW_APPOINTMENT_UPPERCASE: "NUEVA CONSULTA",
    NEW_APPOINTMENT: "NUEVA CONSULTA",
    FIRST_CONSULT: "Primera Consulta",
    HEALTH_CENTER: "Consultorio",
    SAVE: "Guardar",
    FINISH: "Terminar",
    CANCEL: "Cancelar",
    EDIT: "Editar",
    NOTES: "Notas",
    YEAR: "año",
    YEARS: "años",
    MAP: "Mapa",
    EMAIL: "Correo",
    CURRENT_LOCATION: "Localizacion actual",
    SEARCH: "Buscar",
    FINALIZE_APPOINTMENT: "Finalizar consulta",
    FINALIZE: "Finalizar",
    RESCHEDULE: "Reagendar",
    SEARCH_MEDICINE: "Buscar medicamento",
    NEW_PATIENT: "Nuevo Paciente",
    ADD_SOMETHING: "Añade algún",
    PATIENT_INFO_VISIBILITY_SCOPE:
      "Solo son visibles para el profesional de la salud.",
    FIND_PATIENT_BY_NAME_ETC:
      "Buscar paciente por nombre, número de indentidad, email, celular ",
    FIND_PATIENT_BY_NAME: "Buscar paciente",
    CLOSE: "Cerrar",
    SENT_BY_MAIL: "Enviar por correo",
    PRINT: "Imprimir",
    HOME: "Inicio",
    CUSTOMERS: "Pacientes",
    TUTORIALS: "Tutoriales",
    CALENDARS: "Calendario",
    WAITING_ROOM: "Sala de espera virtual",
    PRODUCT: "Servicios y Productos",
    PAYMENT: "Cobros",
    STATISTICS: "Estadísticas",
    ECLINIQ_CHAT: "eCliniq Chat",
    CUSTOMER_SERVICE: "Customer service",
    HER: "La",
    HIM: "El",
    BACK: "Atrás",
    FOLLOW: "Siguiente",
    GENERAL_DATA: "Datos Generales",
    ADDITIONAL_GENERAL_DATA: "Especialidad, idioma, nacionalidad",
    CONTACT_DATA: "Consultorio, Contacto, Seguros asociados",
    CONTACT: "Contacto",
    GENDER: "Género",
    PROFESSION: "Profesión",
    PROFESSION_REQUIRED: "Profesión *",
    POLICY_AND_TERMS: "¿Aceptas nuestros terminos y condiciones?",
    SPECIALTIES: "Especialidades",
    SPECIALTY: "Especialidad",
    LANGUAGES: "Idiomas",
    NATIONALITY: "Nacionalidad",
    IMPORT_PATIENT: "Importar paciente",
    DOWNLOAD_TEMPLATE_1: "Descargar plantilla 1",
    DOWNLOAD_TEMPLATE_2: "Descargar plantilla 2",
    TEMPLATE: "Plantillas",
    RECIPES_CONFIG: "Ajustes de Recetario",
    DIGITAL_SIGNATURE: "Firma Digital",
    DIGITAL_LOGO: "Logo para receta",
    WRITE_URL: "Escribe su url",
    SIGNATURE: "Firmas",
    LOGO: "Logo",
    DR_WEB_URL: "Agrega una URL a tu centro médico",
    DR_SHORT_URL: "Url de web del profesional",
    DR_LOGO: "Logo del profesional",
    DR_SIGNATURE: "Firma del profesional",
    UPDATE: "Actualizar",
    CHOOSE_FILE: "Selecione archivo",
    ADD_FILES: "Agregar archivos",
    CHOOSE_IMAGE: "Selecione una imagen",
    RECOMMENDED_SIZE: "(Dimensiones recomendadas 600 x 200)",
    CARD: "Tarjeta",
    IMPORTED_PATIENTS: "Pacientes importados satisfactoriamente.",
    ACTIVE: "Activo",
    INACTIVE: "Inactivo",
    REQUEST_SEND_SUCCESS: "Mensaje enviado satisfactoriamente",
    REQUEST_SEND_SUCCESS_BY_EMAIL:
      "Documento compartido por email correctamente",
    REQUEST_SEND_SUCCESS_BY_CELL:
      "Documento compartido con el paciente correctamente",
    REQUEST_SEND_SUCCESS_BY_CELL_PATIENT_DOCTOR:
      "Documento compartido con el paciente y profesional correctamente",
    REQUEST_SEND_DOCUMENT_SUCCESS: "Documento compartido correctamente",
    ADD_URL: "Agrega una URL a tu centro médico",
    ADDITIONAL_PUBLIC_GENERAL_DATA: "Especialidades e idiomas",
    PUBLIC_CONTACT_DATA: "Consultorios y Seguros asociados",
    UPLOAD_FILE: "Sube un archivo",
    SUCCESS_CONSENT_FILE: "Consentimiento subido satisfactoriamente",
    UPLOAD_CONSENT: "Consentimiento",
    ADD_CONSENT: "Agregar Consentimiento",
    ADD: "Agregar",
    ALERT: "Alerta",
    SUCCESS_PROFESSIONAL_FILE: "Archivo subido satisfactoriamente",
    UPLOAD_FILE_P12: "Subir archivo de firma .pfx o .p12",
    CONSENT_NAME: "Nombre del consentimiento",
    INVITE_OTHERS: "Invita a otros profesionales",
    INVITE: "Invitar",
    SUCCESS_INVITATION: "Invitacion enviada correctamente",
    HEALTH_CENTERS: "Consultorios",
    SEARCH_CUSTOMER: "Buscar paciente",
    PICK_TIME: "Selecciona la hora",
    PATIENT: "Paciente",
    ID: "Identificación",
    DATE: "Fecha",
    INFO: "Información",
    DUPLICATE_REQUEST: "Duplicar pedido",
    LOGIN: "Inicia sesión",
    NOT_FOUND_PAGE: "Lo sentimos, no se encontró la ruta especificada",
    HISTORY: "Historial",
    CONFIRM: "Confirmar",
    NO_DESCRIPTION: "No hay descripción",
    E_SIGNATURE: "Firma Electrónica",
    SIGNATURE_EXPIRE: "Su firma vence:",
    ADD_E_SIGNATURE: "Debe agregar una firma electrónica",
    CHANGE_E_SIGNATURE: "Agregar o sustituir la firma electrónica",
    SHOW_SIGNATURE_ON_DOCS: "Mostrar firma digital en documentos impresos",
    CHOOSE_CURRENT_HEALTH_CENTER: "Elija su consultorio actual",
    TO_END: "Finalizar",
    NAME_NOTES: "Nombre / Notas",
    INITIAL_DATE: "Fecha de inicio",
    RESET_ATTACHMENTS: "Borrar todos",
    INFORMS: "Informes",
    YES: "Si",
    NO: "No",
    CONFIRM_DELETE_CUSTOMER:
      "¿Deseas eliminar este paciente? Este cambio no se puede revertir.",
    CUSTOMER_DELETE_SUCCESS: "El paciente ha sido eliminado satisfactoriamente",
    WHITE_TEXT_TO_FIND_RESULT: "Escriba un texto para encontar resultados",
    DR: "Dr.",
    DRA: "Dra.",
    PHONE: "Telf:",
    MAIL: "Correo:",
    CI: "CI:",
    AGE: "Edad:",
    MONTH_S: "mes(es)",
    ALLERGIES: "Alergias",
    CERTIFICATE_THAT: "Certifico que ",
    SEND_BY_CUSTOMER_CELL: "Enviar al celular",
    HISTORICAL: "Historial",
    PILLS_ALLERGIES: "Alergias a medicamentos:",
    IMAGES: "Imágenes",
    LAB: "Laboratorio",
    OTHER_REQUESTS: "Otros Pedidos",
    LOW_RESULTS: "Resultados",
    TITLE: "Título ",
    THE_MISSING_FIELD: "Falta el campo ",
  },
  validation: {
    TEXT_VALID_EMAIL: "Escribe un correo válido.",
    TEXT_REGISTERED_EMAIL: "Por favor escribe un correo.",
    VALID_PASSWORD: "Su contraseña no es válida.",
    MINIMUM_EIGHT_CHARACTER: "Mínimo 8 caracteres",
    UPPER_CASE_LETTER: "Letra mayúscula",
    LOW_CASE_LETTER: "Letra minúscula",
    ONE_NUMBER: "Un número",
    CURRENT_PASSWORD: "Escribe tu contraseña actual",
    CREATE_NEW_PASSWORD: "crea una contraseña",
    CONFIRM_PASSWORD: "confirmar la contraseña",
    PASSWORD_MOST_MATCH: "La contraseña debe coincidir",
    EVERY_QUESTION_TO_BE_ANSWERED: "Cada pregunta debe ser respondida",
    WEIGHT_REQUIRED: "Peso es requerido",
    SIZE_REQUIRED: "La talla es requerida",
    MASS_REQUIRED: "La masa es requerida",
    LOW_WEIGHT: "Bajo peso",
    MOST_BE_NUMBER: "Debe ser un número",
    WRONG_PHONE_NUMBER: "Formato de Número Incorrecto",
    NAME_MANDATORY: "El nombre es requerido",
    FIELD_MANDATORY: "Este campo es requerido",
    SELECT_PATIENT: "Error: Seleccione un paciente para agendar la consulta",
    TITLE_RESULT_REQUIRED: "El título del resultado es requerido ",
    DESCRIPTION_RESULT_REQUIRED: "La descripción es requerida",
    OBSERVATION_RESULT_REQUIRED: "Las observaciones son requeridas",
    ANALYSIS_RESULT_REQUIRED: "El análisis es requerido",
    FILE_RESULT_ATTACHMENT_REQUIRED: "El archivo del resultado es requerido",
    MISSING_ALL_FIELDS: "Faltan todos los campos necesarios",
  },
  appointment: {
    TODAY: "Día de hoy",
    WHAT_DO_YOU_DO_IN_APPOINTMENT: "¿Qué desea hacer en la consulta?",
    PRESENTIAL_APPOINTMENT: "Cita presencial",
    PROGRAMED_APPOINTMENT_VIRTUAL: "Cita virtual programada",
    VIRTUAL_APPOINTMENT: "Cita virtual",
    VIRTUAL_APPOINTMENT_INFO:
      "Estás agendando una consulta en la modalidad de: ",
    VIRTUAL_WATING_ROOM: "Sala de espera virtual",
    CONGRESS_AND_ECLINIQ_SOCIAL: "Congresos - Grand Rounds, eCliniq Social",
    DG: "Dg",
    TTO: " Tto",
    APPOINTMENT_HISTORY: " HISTORIAL DE CONSULTAS",
    DO_YOU_WANT_TO_CANCEL_THE_APPOINTMENT: "¿Desea cancelar la consulta?",
    APPOINTMENT_SCHEDULE: " CONSULTAS AGENDADAS",
    APPOINTMENT_DATE: "Fecha de la cita",
    APPOINTMENT_TIME: "Hora de la cita",
    APPOINTMENT_DURATION: "Duración de la cita",
    APPOINTMENT_HEALTH_CENTER: "Consultorios",
    APPOINTMENT_SPECIALTIES: "Especialidad",
    APPOINTMENT_REASON_PLACEHOLDER: "Motivo de la consulta",
    APPOINTMENT_REASON: "Motivo",
    NEW_APPOINTMENT: "Nueva Consulta",
    REMOTE_CHANGE: "Cambiar a teleconsulta",
    FIRST_TIME: "Primera cita",
    DELETE_APPOINTMENT: "Cancelar cita",
    ABSTRACT_APPOINTMENT: "Resumen de la cita",
    START_DATE: "Fecha de inicio",
    START_TIME: "Hora inicio",
    END_DATE: "Fecha fin",
    END_TIME: "Hora fin",
    LOCK_SCHEDULE_SUCCESS: "Calendario bloqueado con éxito",
    UNLOCK_SCHEDULE_SUCCESS: "Calendario habilitado con éxito",
    PLAY_IN: "Ingresar",
    LOCK_SCHEDULE: "Bloquear horario",
    UNLOCK_SCHEDULE: "Habilitar horario",
    AVAILABILITY_SCHEDULE_INFO:
      "Habilita horarios para que aparezcan como disponibles y que los pacientes puedan agendar citas",
    DATE_TO_AVAILABLE: "Fecha por habilitar",
    TIME_TO_AVAILABLE: "Horas por habilitar",
    RESCHEDULE: "Reagendar",
    RESCHEDULE_INFO:
      "¿Estás seguro que quieres reagendar la cita? Este cambio no se puede revertir.",
    CHANGE_APPOINTMENT_MODE_INFO:
      "¿Quieres cambiar esta cita a la modalidad de Cita Virtual? Este cambio no se puede revertir.",
    UNLOCK_INFO:
      "¿Estás seguro que quieres habilitar este horario? Este cambio no se puede revertir.",
    IN_PROGRESS: "En progreso",
    PAID: "Pagada",
    PENDENT: "Pendiente",
    PAYMENTS: "COBROS",
    SURE_DELETE_APPOINTMENT: "Desea eliminar cita",
    CANCEL_INFO:
      "¿Estás seguro que quieres cancelar la cita? Este cambio no se puede revertir.",
    INFORM_APPOINTMENT: "Información de la cita",
    TO_JOINT_APPOINTMENT: "Ingresar a la consulta",
    SAVED_VITAL_SIGNS: "Signos vitales guardados correctamente",
    SAVED_ILLNESS_HISTORY: "Historia guardada correctamente",
    SAVED_BODY_TEST: "Examen Físico guardado correctamente",
    SAVED_ANALYSIS_DIAGNOSIS: "Análisis-Diagnóstico guardado correctamente",
    SAVED_BILLS: "Cobros guardados correctamente",
    CREATE_APPOINTMENT_SUCCESS: "Cita creada correctamente",
    NOT_VALID_DATE: "La fecha seleccionada no es válida",
    SCHEDULE: "Agendada",
  },
  allergies: {
    ALLERGIES: "ALERGIAS",
    PILLS_OR_PRODUCTS: "Medicamentos o Productos",
    OTHER_ALLERGIES: "OTRAS ALERGIAS",
    NO_ALLERGIES: "La paciente no refiere alergias conocidas",
    ALLERGIES_TITLE: "ALERGIAS A MEDICAMENTOS O PRODUCTOS",
    FIND_MEDICINE: "Buscar Medicamento",
    CANCEL: "Cancelar",
    SAVE: "Guardar",
    NO_ALLERGIES_LABEL: "paciente no refiere alergias conocidas",
    NO_OTHER_ALLERGIES: "No Presentan otras alergias",
    NO_ALLERGIES_NO_PATIENT: "No refiere alergias conocidas",
    DON_T_ADD_ALLERGIES_YET: "No se han agregado alergias todavía",
    UNDEFINED_ALLERGIES: "Sin definir",
  },
  patientInfo: {
    SEX: "Sexo",
    TYPE_BLOOD: "Tipo de Sangre",
    ID: "Nro Identidad",
    EMAIL: "Correo",
    CELL: "Celular",
    PHONE: "Teléfono",
    RECORD: "Expediente",
    CITY: "Ciudad",
    ADDRESS: "Dirección",
    MEDICAL_INSURANCE: "Seguro",
    EMERGENCY: "Emergencia",
    MARITAL_STATUS: "Estado Civil",
    OCCUPATION: "Prof/Ocupación",
    CI: "CI",
    PATIENT_YEAR_CREATION: "Año creación de paciente",
  },
  background: {
    BACKGROUND: "ANTECEDENTES",
    SURGICAL_BACKGROUND: "ANTECEDENTES QUIRÚRGICOS",
    PERSONAL_BACKGROUND: "ANTECEDENTES PATOLÓGICOS PERSONALES",
    PSYCHIATRIC_BACKGROUND: "ANTECEDENTES PSIQUIÁTRICOS",
    FAMILY_BACKGROUND: "ANTECEDENTES PATOLÓGICOS FAMILIARES",
    HABITS_BACKGROUND: "HÁBITOS",
    FEMALE_PATIENT: "La paciente",
    MALE_PATIENT: "El paciente",
    OTHER_PATIENT: "Paciente",
    DON_T_REF_SURGICAL: "no refiere cirugías conocidas",
    DON_T_REF_PATHOLOGY: "no refiere patologías conocidas",
    DON_T_REF_HABITS: "no refiere hábitos conocidos",
    DON_T_REF_FAMILY_PATHOLOGY:
      "no refiere familiares con patologías conocidas",
    DON_T_REF_PSYCHIATRIC: "no refiere antecedentes psiquiátricos conocidos",
    DON_T_REF_ALLERGY: "no refiere alergias conocidas",

    DESCRIBE_THE_SURGICAL: "Describe la cirugía",
    NUTRITION_BACKGROUND: "HISTORIAL DE NUTRICIÓN",
    MENSTRUATION_CHARACTERISTIC: "Característica de la menstruación",
    CONTRACEPTIVE_METHOD: "Método Anticonceptivo",
    SEXUALLY_TRANSMITTED_DISEASE: "Enf. transmisión sexual",
    GYNECOLOGICAL_OBSTETRIC_BACKGROUND: "ANTECEDENTES GINECO-OBSTÉTRICOS",
    MENARCHE: "Menarquía",
    THELARCHE: "Telarquía",
    START_SEX_LIFE: "Inicio de vida sexual",
    AGE: "Edad",
    PREGNANCIES: "Gestas",
    CAESAREANS: "Cesáreas",
    ABORTIONS: "Abortos",
    CHILDBIRTHS: "Partos",
    LIVING_CHILDREN: "Hijos vivos",
    LAST_MENSTRUATION: "Última menstruación",
    LAST_MENSTRUATION_DATE: "Fecha última menstruación",
    FUM: "FUM",
    DETAILS: "DETALLES",
    SEXUAL_ACTIVITY: "Actividad sexual",
    SURGICAL: "Cirugía",
    FAMILY_MEMBER: "Miembro de la familia",
    PATHOLOGIES: "Patologías",
    HABITS: "Hábitos",
    PSYCHIATRIC_BACKGROUND_PLACEHOLDER: "Antecdente psiquiátrico",
    DONT_SHOW_MEDICATION: "No hay medicamentos para este paciente",
    ACTIVE_MEDICATION: "Medicamentos Activos",
  },
  nutrition: {
    DAILY_GLASSES_NUMBER: "Vasos de agua al día",
    APPETITE_LEVEL: "Nivel de apetito",
    NUTRITION_HABITS: "Hábitos alimenticios",
  },
  vaccinationScheme: {
    VACCINATION_SCHEMA: "ESQUEMA DE VACUNACIÓN",
    WRITE_HERE: "Escribe aquí",
  },
  interconsult: {
    NEW_INTERCONSULT: "Nueva Interconsulta",
    NEW_CONSULT: "Nueva Consulta",
    INTERCONSULT_REPORT: "INFORME DE INTERCONSULTA",
    HISTORICAL_INTERCONSULT: "HISTORIAL DE INTERCONSULTAS",
    ABSTRACT: "RESUMEN DE INTERCONSULTA",
    CLINICAL_CRITERIAL: "RESUMEN DE CRITERIO CLINICO",
    CLINIC_PROFILE: "CUADRO CLÍNICO DE ENFERMEDAD *",
    PHISICAL_EXAM: "EXAMEN FÍSICO Y SIGNOS VITALES",
    ANALISYS: "ANÁLISIS",
    TREATMENT: "PLAN Y TRATAMIENTO",
    EXAM_PROCEDURE: "EXÁMENES Y PROCEDIMIENTOS DIAGNÓSTICOS",
    BACKGROUND: "ANTECEDENTES (APF, APP, AQ, AGO, HÁBITOS) *",
    OBSERVATIONS: "OBSERVACIONES",
    ATTACHMENT: "ARCHIVOS ADJUNTOS",
    PROFESSIONAL_SPECIALTIES: "Elija la especialidad",
    FROM_PROFESSIONAL: "Profesional que interconsulta",
    REASON: "Motivo de la interconsulta",
    INTERCONSULT_SHEET: "Ficha de Interconsulta",
    INTERCONSULT_MAKE_INFORM: "Realizar Informe",
    INTERCONSULT_INFORM: "Informe",
    TO_PROFESSIONAL: "Profesional interconsultado",
    EMERGENCY: "Urgente",
    NORMAL: "Normal",
    RECEIVED: "INTERCONSULTAS RECIBIDAS",
    MADE_BY_ME: "INTERCONSULTAS REALIZADAS POR MI",
    NOT_RESULTS: "No hay interconsultas para mostrar",
    WITH_OUT_REPORT: "Esta interconsulta aún no tiene respuesta",
  },
  error: {
    ERROR: "Error",
    UNKNOWN_ERROR: "Error desconocido",
    CHOOSE_LOCATION: "Debe seleccionar una ubicación",
    INTERNET_CONNECTION_PROBLEM:
      "Se ha detectado problemas en la conexión a internet, por favor inténtelo más tarde",
    YOU_CANT_EDIT_USER:
      "El paciente está registrado en la app, para modificar los datos debe ingresar con las credenciales del paciente",
    CACHE_ERROR:
      "Un error en nuestra cache ha ocurrido, por favor contacte a nuestro administrador.",
    NEEDED_CODE: "El código es necesario",
    ONLY_NUMBERS: "Solo números",
    ONLY_ONE_DIGIT: "Debe tener 1 dígito",
    CHOOSE_DIAGNOSE: "Debe agregar un diagnóstico",
    CHOOSE_ADD_DETAILS_DIAGNOSE: "Debe agregar los detalles del diagnóstico",
    SAME_KEYWORD: "Ambas contraseñas tienen que coincider",
    NUMBER_RANGE: "El numero debe estar entre 4 -20 dígitos",
    ACCEPTED_TERMS_ERROR: "Debe aceptar los términos de la plataforma",
    ONLY_LETTERS: "Solo letras",
    CHOOSE_PROFESSION: "Debe agregar su profesión",
    CHOOSE_GENDER: "Debe agregar su género",
    ABOUT_ME_GENDER: "Debe agregar información acerca de usted",
    CHOOSE_SPECIALTY: "Debe agregar su(s) epecialidades",
    CHOOSE_HEALTH_CENTER: "Debe agregar su(s) consultorios",
    INSURANCES_CENTER: "Debe agregar su(s) seguros",
    CURRICULUM_CENTER: "Debe agregar su(s) hospitales",
    HOSPITALS_CENTER: "Debe agregar información sobre su currículum",
    CHOOSE_CITY: "Debe agregar una ciudad",
    CHOOSE_PHONE: "Debe agregar un teléfono",
    CHOOSE_INSURANCE: "Debe agregar un seguro",
    NAME_REQUIRED: "El nombre es requerido",
    LAST_FAMILY_NAME_REQUIRED: "El primer apellido es requerido",
    EMAIL_REQUIRED: "El correo es requerido",
    LEGAL_ID_REQUIRED: "El nro de identidad es requerido",
    CELL_REQUIRED: "El celular es requerido",
    FIELD_REQUIRED: "Este campo es requerido",
    REQUIRED: "Requerido",
    WRITE_YOUR_ID_REQUIRED:
      "El Documento de identidad (cédula, pasaporte) es requerido",
    VALID_DATE_INTRODUCE: "Rectifique los datos introducidos en este panel",
    ALL_PANEL_SALVED: "Todos los paneles deben ser guardados",
    REQUEST_VALIDATE_MESSAGE:
      "Por favor llene todos los campos (Diagnóstico y Pedido)",
    REQUEST_CODE_REQUIRED: "El código de la petición está indefinido",
    MISSING_FIELD: "Error: Faltan campos para la receta",
    DON_T_EXIST_TEMPLATE_TO_SELECTED_INSURANCE:
      "No existe plantilla para el seguro seleccionado",
    SHOULD_ADD_DETAILS: "Debe agregar detalles",
    UPLOAD_FILE_FIRST: "Debe subir un archivo antes de continuar",
    ADD_PROCEDURE_NAME: "Nombre de procedimiento",
    NOT_AUTHORIZED: "No está autorizado a acceder a este recurso",
    INVALID_DISCOUNT: "Error: El descuento no puede ser menor que el subtotal",
    ERROR_AT_LINE: "en la fila # ",
    MAX_255_CHARACTERS: "Escriba un máximo de 255 caracteres",
    REQUEST_VALIDATE_ANALYSIS_MESSAGE:
      "Por favor añade los análisis y diagnósticos",
    REQUEST_VALIDATE_LAB: "Por favor añade algún pedido de laboratorio",
    REQUEST_VALIDATE_IMAGE: "Por favor añade algún pedido de imagen",
    QUANTITY_MUST_BE_GREATER_THAN_CERO: "La cantidad debe ser mayor que 0",
    DOSE_MUST_BE_GREATER_THAN_CERO: "La dosis debe ser mayor que 0",
    MUST_BE_GREATER_THAN_CERO: "Mayor que 0",
    NO_DIAGNOSIS: "Faltan los diagnósticos",
    NO_PILLS: "Faltan los medicamentos",
    CHOOSE_ADD_DETAILS_CERTIFICATE: "Debe agregar los detalles del Certificado",
  },
  buttonGrid: {
    RX_REQUESTS: "Pedidos de Imágenes",
    LAB_REQUESTS: "Pedidos de Laboratorios",
    HISTORY_REQUESTS: "Historial de pedidos de laboratorio",
    RESULTS: "Resultados",
    LAB_PANEL: "PANELES DE LABORATORIO",
    OTHER_REQUEST: "Otros Pedidos",
    INTER_CONSULT: "Interconsultas",
    DIAGNOSIS: "DIAGNÓSTICO(S)",
    REQUESTS: "PEDIDO ",
    SEARCH_REQUESTS: "Agregar pedido",
    SEARCH_DIAGNOSE: "CIE 10 o diagnóstico manual",
    PRESUMPTIVE: "Presuntivo",
    DEFINITIVE: "Definitivo",
    RECIPES: "Recetas",
    CERTIFICATE: "Certificados",
    NEW_INTER_CONSULT: "NUEVA INTERCONSULTA",
    HISTORICAL_INTER_CONSULT: "HISTORIAL DE INTERCONSULTA",
    FILES: "Archivos",
    FILE: "Archivo",
    INSURANCES: "Seguros",
    INFORM_CONSENTS: "Consentimientos Informados",
    CONSENT: "Consentimientos Informados",
    REPORT: "Informes",
    INTER: "Interconsulta",
    PROCEDURE: "Procedimiento",
  },
  signupCustomer: {
    NEW_CUSTOMER: "Nuevo Paciente",
    NAME: "Nombre",
    NAME_REQUIRED: "Nombre *",
    LAST_NAME: "Segundo Nombre",
    FIRST_FAMILY_NAME: "Primero Apellido *",
    LAST_FAMILY_NAME: "Segundo Apellido",
    DATE_OF_BIRTHDAY: "Fecha de Nacimiento *",
    GENDER: "Género",
    ID: "Número de Identidad *",
    PERSONAL_EMAIL_FAMILY: "Correo electrónico personal o familiar *",
    CELL: "Celular",
    CELL_REQUIRED: "Celular *",
    DEFAULT_PREFIX: "+593",
    PHONE: "Teléfono",
    BLOOD_TYPE: "Tipo de Sangre",
    NUMBER_EXPEDIENT: "Número de expediente médico",
    MARITAL_STATUS: "Estado Civil",
    OCCUPATION: "Profesión / Ocupación",
    PATIENTE_TYPE: "Tipo de paciente",
    DEMOGRAPHIC_INFORMATION: "Información Demográfica",
    ADDRESS: "Dirección",
    COUNTRY: "País",
    PROVINCE: "Provincia",
    CITY: "Ciudad",
    ADDRESS_NOTES: "Piso, departamento y otras notas",
    APT: "Apto",
    INSURANCE_TITLE: "Seguro",
    INSURANCE: "Aseguradora",
    POLICY_NUMBER: "Número de Póliza",
    INVOICE_DATA: "Datos de Facturación",
    SOCIAL_REASON: "Razón Social",
    DOCUMENT: "RUC/Cédula",
    EMERGENCY_CONTACT: "Contacto de Emergencia",
    RELATIONSHIP: "Parentesco",
    CELL_PHONE_EMERGENCY: "Teléfono/Celular",
    ADDRESS_EMERGENCY_CONTACT: "Dirección de Contacto de Emergencia",
    SAVE_CUSTOMER: "Guardar Paciente",
    COMPLETE_CUSTOMER: "Completar con datos de paciente",
    CUSTOMER_EDITED_SUCCESS: "El Paciente fue actualizado satisfactoriamente",
    CUSTOMER_CREATED_SUCCESS: "El Paciente fue creado satisfactoriamente",
    YOU_CAN_VERIFY_PATIENT_CI_IN_THIS_LINK:
      "Puede verificar el nro de indetidad del paciente en el siguiente enlace:",
    NO_NOTIFICATION_NOTE:
      "Al seleccionar esta opción, no se podrán enviar los documentos: recetas, pedidos, informes o cualquier otro documentado generado en el sistema",
    WITHOUT_EMAIL: "Sin Email",
  },
  recovery: {
    NOT_YET: "¿No te llegó el correo? Reenviar",
    FORGOT_KEYWORD: "¿Olvidaste tu contraseña?",
    WRITE_YOUR_MAIL: "Escribe su email",
    CONFIRM: "Confirmar",
    VALIDATE: "Validar",
    CHECK_YOUR_MAIL: "Verificación de tu correo electrónico",
    SENT_TO: "Se ha enviado un correo electrónico a: ",
    RESENT_CODE: "Se ha reenviado el código a su correo electrónico",
    WRONG_MAIL: "Correo Incorrecto",
    NEW_KEYWORD: "Nueva contraseña",
    CONFIRM_NEW_KEYWORD: "Confirme su contraseña",
    AT_LEAST_LOWERCASE: "Al menos una letra en minúscula",
    AT_LEAST_UPPERCASE: "Al menos una letra en mayúscula",
    AT_LEAST_NUMBER: "Al menos un número",
    MIN_LENGTH: "Al menos 8 letras",
    REQUIRED_KEYWORD: "Su clave es requerida",
    WRITE_PIN: "Ingresa el código de verificación",
    NEEDED_MAIL: "Su correo es requerido",
    FIRST_DIGIT: "1er dígito",
    SECOND_DIGIT: "2do dígito",
    THIRD_DIGIT: "3er dígito",
    FOURTH_DIGIT: "4to dígito",
    KEYWORD: "Contraseña",
    SIGNATURE_KEYWORD: "Clave de firma electrónica",
  },
  register: {
    ADD_NEW_USER: "Crea un usuario",
    CHECK_EMAIL: "Verificar correo electrónico",
  },
  historical: {
    PATIENT_NAME: "Paciente: ",
    INTER_CONSULTER_PROFESSIONAL: "Profesional que interconsulta: ",
    INTER_CONSULTER_REASON: "Motivo de la interconsulta: ",
    DIAGNOSES: "Dg: ",
    LOWER_REQUEST: "Pedido: ",
    REQUEST: "Pedido: ",
    TIME: "Hora: ",
    DATE: "Fecha: ",
    DIAGNOSE_WORD: "diagnóstico",
  },
  signUp: {
    NEW_USER: "Crear cuenta gratuita",
    FIRST_NAME_MANDATORY: "Su primer nombre es requerido",
    FIRST_FAMILY_NAME_MANDATORY: "Su primer apellido es requerido",
    LAST_FAMILY_NAME_MANDATORY: "Su segundo apellido es requerido",
    MIN_LENGTH: "Al menos 3 letras",
    MIN_ID_LENGTH: "Al menos 6 letras",
    WRITE_YOUR_NAME: "Primer Nombre *",
    WRITE_YOUR_FIRST_FAMILY: "Primer Apellido *",
    WRITE_YOUR_LAST_FAMILY: "Segundo Apellido",
    WRITE_YOUR_LAST_NAME: "Segundo Nombre",
    WRITE_YOUR_ID: "Documento de identidad (cédula, pasaporte) *",
    WRITE_YOUR_PROFESSIONAL_ID_REQUIRED: "Nro Registro profesional *",
    WRITE_YOUR_PROFESSIONAL_ID: "Nro Registro profesional",
    HEALTH_CENTER_TITLE: "Consultorio, Contacto, Seguro",
    PROFESSIONAL_EMAIL_TITLE:
      "Correo de contacto. Puede ser el mismo de registro",
    REGISTER: "Registrar",
    GENDER: "Género",
    PROFESSION: "Profesión",
    PRO_MAIL: "Email Profesional",
    RESIDENCE_CITY: "Ciudad de residencia",
    RESIDENCE_PROVINCE: "Provincia de residencia",
    ADD_NUMBER_PREFIX: "Agregue un prefijo",
    ADD_PHONE_NUMBER: "Nro de Teléfono",
    ADD_PHONE_TYPE: "Agregue un tipo de teléfono",
    PHONES: "Teléfonos",
    NOT_PHONE_ASSOCIATED: "No hay teléfonos asociados",
    PHONE_TYPE: "Tipo de Contacto",
    PERSON_TO_CONTACT: "A quien contactar",
    ADD_PHONE: "Agrega un Telf.",
    BE_PUBLIC: "¿Quieres mostrar los Teléfonos Asociados a tu consultorio",
    YOUR_PROFILE:
      "en tu perfil profesional con el fin que los pacientes lo vean?",
    ADD_INSURANCE: "¿Agregara un seguro_?",
    CELL_NUMBER: "Número de celular",
    ASSOCIATED_INSURANCES: "Seguros Asociados",
    NOT_INSURANCES_ASSOCIATED: "No hay seguros asociados",
    ADD_INSURANCES: "Asociar nuevo seguro",
    CONSULTING_ROOM: "Consultorios",
    ADD_CONSULTING_ROOM:
      "Agregar Consultorios (optimiza la receta, pedidos, etc.)",
    CHOOSE_CONSULTING_ROOM: "Elija sus Consultorios",
    ADD_HOSPITALS: "Agregar Hospitales",
    NO_CONSULTING_ROOM: "Sin consultorios asociados",
    SPECIALTIES: "Especialidades",
    NO_SPECIALTIES: "Sin Especilidades asociadas",
    CHOOSE_LANGUAGE: "Escoja un idioma",
    DR_PROFILE: "Perfil Profesional",
    ABOUT_ME: "Acerca de mi",
    WORKING_MEDICAL_CENTERS: "Afiliaciones Hospitales / Clínicas",
    HOSPITALS: "Hospitales",
    NO_HOSPITALS: "Sin hospitales asociados",
    ACCEPTED_TERMS_ONE: "Acepto los ",
    ACCEPTED_TERMS_TWO: "términos, condiciones",
    ACCEPTED_TERMS_THREE: "y políticas de privacidad.",
    DECLARE_TRUTH:
      "Declaro que la información proporcionada es veraz y aunténtica, y que cualquier omisión o inexactitud que pueda ocasionar perjuicios a terceros o a mi persona serán de mi entera responsabilidad",
    DECLARE_TRUTH_SECOND:
      "omisión o inexactitud que pueda ocasionar perjuicios a terceros o a mi persona serán de mi entera responsabilidad",
    ACCEPT_TO_BE_CONTACT:
      "Acepto ser contactado a través de mi teléfono o correo electrónico.",
    CURRICULUM_DESCRIPTION: "Describe su currículum",
    CURRICULUM: "Currículum",
    NO_CURRICULUM: "Sin elementos de currículum",
    LIFE_WORK: "Agrege los elementos más destacados sobre su hoja de vida",
    BIRTH_DATE: "Fecha de Nacimiento",
    UPDATE_PROFILE: "Actualiza tu perfil",
    INVITE_ASSISTANT: "Invitar Asistente",
    MAIN_EMAIL: "Correo electrónico principal",
    NAME_LAST_NAME: "Nombre y Apellido",
  },
  recipe: {
    PRESCRIPTION: "PRESCRIPCIÓN",
    INDICATIONS: "INDICACIONES",
    GENERIC_CONCENTRATION: "Genérico",
    COMMERCIAL_CONCENTRATION: "Comercial",
    CONCENTRATION: "Concentración",
    PRESENTATION: "Presentación",
    AMOUNT: "Cantidad",
    WAY_ADMINISTRATION: "Vía de Administración",
    WAY: "vía",
    DOSE: "Dosis",
    FREQUENCY: "Frecuencia",
    DURATION: "Duración",
    REDACT_INDICATIONS: "Redactar Indicaciones",
    RECOMMENDATIONS: "Recomendaciones:",
    ALARM: "Signos de Alarma",
    PRESCRIPTION_LOW: "Indicaciones:",
    INDICATIONS_LOW: "Prescripción:",
    HOUR: "hora",
    HOURS: "horas",
    DAY: "día",
    DAYS: "días",
    WEEK: "semana",
    WEEKS: "semanas",
    MONTH: "mes",
    MONTHS: "meses",
  },
  newConsult: {
    ACTUAL_ILLNESS: "ENFERMEDAD ACTUAL",
    MOTIVE_CONSUL: "MOTIVO DE CONSULTA",
    HISTORY_ILLNESS: "HISTORIA NATURAL DE LA ENFERMEDAD",
    ANALYSIS_DIAGNOSES: "ANÁLISIS - DIAGNÓSTICO",
    DIAGNOSES: "DIAGNÓSTICO(S)",
    VITAL_SIGNS:
      "SIGNOS VITALES (Se muestran los últimos SV. Se copian a una nueva consulta)",
    WEIGHT: "Peso",
    HEIGHT: "Estatura",
    IMC: "IMC (kg/m2)",
    TEMPERATURE: "Temp (°C)",
    HEART_FREQUENCY: "F. Cardiaca (lat/min)",
    RESPONSE_FREQUENCY: "F. Resp (res/min)",
    SYSTOLIC: "Sistólica (mmHg)",
    DIASTOLIC: "Diastólica (mmHg)",
    SATURATION_O2: "Sat. de O2 (%)",
    BODY_MASS: "Masa Musc",
    FAT_BODY: "% Grasa Corp",
    CEFALICO: "Perímetro Cefálico",
    ORDER_IMAGEN: "PEDIDO DE IMAGEN",
    TREATMENT_PLAN: "PLAN - TRATAMIENTO",
    ORDER_CABINET: "PEDIDOS DE GABINETE",
    ORDER_LABORATORY: "PEDIDO DE LABORATORIO",
    PANEL_LABORATORY: "PANELES DE LABORATORIO",
    PROCESS: "PROCEDIMIENTOS",
    TREATMENT_OF_PLAN: "PLAN DE TRATAMIENTO",
    RECIPE: "RECETA",
    PHYSICAL_EXAM: "EXAMEN FÍSICO",
    EXPLORATION_BY_SYSTEM: "EXPLORACIÓN POR SISTEMAS",
    TOPOGRAPHIC_EXPLORATION: "EXPLORACIÓN TOPOGRÁFICA",
    WRITE_CONSULT_REASON: "Escribe el motivo de la consulta",
    VIRTUAL_CONSULTATION: "Consulta Virtual",
    FACE_TO_FACE_CONSULTATION: "Consulta Presencial",
    PAYMENTS: "COBROS",
    TREATMENT_PLAN_SUCCESS:
      "El plan de tratamiento ha sido agregado correctamente.",
    ERROR_PRESCRIPTION_VALUES: "La prescripción tiene valores incorrectos.",
    CM: "cm",
  },
  request: {
    REQUEST_TYPE: "Tipo de pedido",
  },
  result: {
    DESCRIPTION: "DESCRIPCIÓN DE RESULTADOS",
    ANALISYS: "ANÁLISIS",
    OBSERVATIONS: "OBSERVACIONES",
    ASSISTANT_LIST: "LISTA DE ASISTENTES",
    ADD_RESULT: "Agregar Resultados",
    ADD_ONE_RESULT: "Agregar un Resultado",
    RESULT_TYPE: "Título del resultado",
    CHOOSE_REQUEST_TO_UPLOAD_RESULT:
      "Elija el pedido para subirle un resultado",
    NEW_RESULT: "Nuevo Resultado",
    UPLOAD_RESULT: "Subir Resultado",
    SUMMARY_RESULT: "RESUMEN DEL RESULTADO",
    RESULT_FILE: "Archivo del resultado",
  },
  professionalProfile: {
    CHANGE_PASSWORD: "Cambiar contraseña",
    PROFILE: "Perfil",
    PRICE_WARNING:
      "El precio de la consulta lo puedes editar en Ajustes de    Cuenta - Modalidades de Consulta.",
    DASH: " - ",
    LEGAL_ID: "Número de Registro Profesional",
    SERVICES_TRADE: "Tarifa por servicios",
    HEALTH_CENTER_ASOCIATION: "Afiliación Hospitales / Clínicas",
    SPANISH: "Español",
    ENGLISH: "Inglés",
    WRITE_REVIEW: "Escribir Reseña",
    TO_CHANGE_DATA_SEND_EMAIL:
      "Para cambiar el correo electrónico principal, profesión, o número de registro profesional envíanos por favor un ",
  },
  certificates: {
    NEW_CERTIFICATE: "Nuevo Certificado",
    CERTIFICATE_HISTORY: "Historial de certificados",
    CERTIFICATE_DETAILS: "DETALLES DEL CERTIFICADO",
    CERTIFICATE_RESUME: "RESUMEN DE CERTIFICADO",
  },
  account: {
    MY_ACCOUNT: "Mi Cuenta",
    PLAN_PAY: "Planes y  Pagos",
    ASSISTANT: "Asistentes",
    RECIPE: "Certificados y Recetas",
    ASSISTANT_LIST: "Listado de Asistentes",
    ASSISTANT_MANAGEMENT: "Gestión de asistente",
    EDIT_PUBLIC_ACCOUNT: "Edita tu perfil",
    SUCCESS_PUBLIC_PROFILE_UPDATED: "Perfil público actualizado correctamente",
    UPDATED_AVATAR: "Avatar Actualizado correctamente",
    UPDATED_CORRECTLY: "Actualizado correctamente",
    SHORTY: "próximamente",
  },
  payPlan: {
    PAY_PLAN_TITLE: "Planes y Pagos",
    CURRENT_PLAN: "Plan actual",
    AVAILABLE_PLAN: "Planes disponibles",
    SUBTOTAL: "Subtotal",
    IVA: "IVA",
    DISCOUNT: "Descuento",
    TOTAL: "Total",
    EXPIRE_PLAN_DATE: "Fecha de expiración: ",
    EXPIRE_PLAN_DATE1: "Fecha de culminación del plan vigente: ",
    START_PLAN: "Fecha de inicio del nuevo plan: ",
    ACTIVATE: "Activar",
    NOT_PAYMENT_CARD: "No existe ninguna tarjeta asociada.",
    PAY_NOW: "Pagar ahora",
    ADD_PAYMENT_CARD: "Agregar tarjeta",
    PICK_CARD: "Selecciona una tarjeta",
    PLAN_CREDIT: "Crédito del plan vigente: ",
    TOTAL_PAY: "Total a pagar por el nuevo plan: ",
    EXPIRE_DATE_DAYS: "Días disponibles: ",
    DAYS: "días",
    EXPIRED_PLAN: "Su plan ha expirado",
    NOT_SUBSCRIBED_MESSAGE:
      "Tu suscripción ha expirado, para activarla ingresa a Link Ajustes de Cuenta->Planes.",
    STARTED_PLAN_DATE: "Fecha de inicio del plan: ",
    BENEFITS: "Beneficios",
    OTHER_BENEFITS: "Otros beneficios",
    INCLUDE: "Incluye",
    NOT_INCLUDE: "No incluye",
    NOT_INCLUDE_EXTRA: "No incluye además",
  },
  payment: {
    INVALID_CARD: "Tarjeta no válida",
    INSERTION_CARD_ERROR:
      "Ocurrió un error inesperado en la inserción de la tarjeta.",
    SUCCESS_PAY: "Pago realizado con éxito",
    REGISTERED_PAY_WAY: "Forma de pago registrada",
  },
  schedule: {
    CONFIG_DATA_INFO: "Estás configurando los horarios de: ",
    ATTENTION_SCHEDULE: "Horario de atención",
    ATTENTION_DELAY_TIME: "Duración estándar de la cita",
    ATTENTION_SCHEDULE_INFO:
      "Para cada consultorio, selecciona los bloques de hora en la que los pacientes pueden agendar citas contigo.",
    REMOTE_APPOINTMENT: "Teleconsulta",
    REMOTE_SERVICE: "REMOTE",
    FACE_TO_FACE_SERVICE: "FACE_TO_FACE",
    CHANGE_CONFIG_INFO:
      "Si cambias la duración estándar de cita perderás la configuración de horarios que actualmente tienes. ¿Estás seguro que quieres continuar?",
    WRONG_RANGE:
      "Existen rangos de fechas con hora de inicio y fin iguales. Por favor corriga su configuración.",
    FUTURE_WRONG_RANGE:
      "Cambio no permitido, la configuración quedaría con horarios inconsistentes.",
    DURATION_INFO:
      "Este parámetro no puede editarse si ya existen citas reservadas.",
    CALENDAR: "Calendario",
    AVAILABILITY_CONFIG: "Configurar disponibilidad",
    SELECTED_CUSTOMER: "Paciente seleccionado.",
    SUCCESS_RESCHEDULE: "La cita se ha reagendado correctamente",
    SUCCESS_CANCEL: "La cita se ha cancelado correctamente",
  },
  reports: {
    NEW_REPORT: "Nuevo Informe",
    REPORTS_HISTORY: "Historial de informes",
    DESCRIPTION_REPORT: "DESCRIPCION DEL INFORME",
    HISTORY_REPORT: "HISTORIAL DE INFORMES",
    DETAILS: "Detalles",
    DETAILS_INFORM: "DETALLES DEL INFORME",
    REPORT_RESUME: "RESUMEN DE INFORME",
    SEND_REPORT_SUCCESS: "El Informe fue enviado",
  },
  faqs: {
    LOOKING_FOR_FAQs: "Buscar preguntas",
  },
  service: {
    NAME: "Nombre del servicio o producto",
    CODE: "Código del servicio o producto",
    PERCENT: "(IVA) Porcentaje",
    PRICE: "Precio del servicio o producto (sin IVA)",
    HEALTH_CENTER: "Consultorio",
    NEW_SERVICE: "Nuevo servicio",
    SERVICE: "Servicio o Producto",
    IMPORT_SERVICES: "Importar lista de servicios de excel",
    DOWNLOAD_SERVICE_TEMPLATE: "Descargar ejemplo",
    DESCRIPTION: "Descripción",
    PRODUCT_TYPE: "Tipo de servicio",
    ACTIVE: "Activo",
    SUCCESS: "Servicio (Creado / Editado) satisfactoriamente.",
    DELETE_SUCCESS: "Servicio eliminado satisfactoriamente.",
    FILTER_BY_NAME: "Buscar (nombre/código)",
    SUCCESS_IMPORTED_SERVICES: "Servicios importados satisfactoriamente.",
    SEARCH_SERVICE_PRODUCT: "Buscar servicio o productos",
    ADD_SERVICE_PRODUCT: "Agregar servicio o productos",
  },
  procedure: {
    PROCEDURE: "Procedimientos",
    PROCEDURE_HISTORY: "Historial de Procedimientos",
    NEW_PROCEDURE: "Nuevo Procedimiento",
    PROCEDURE_DETAILS: "Detalles del Procedimiento",
    FIND_EXISTENT_PROCEDURE: "Buscar un procedimiento existente",
    PROCEDURE_RESUME: "Resumen de procedimiento",
    NAME_PROCEDURE_REQUIRED: "nombre del procedimiento es requerido",
    NAME_PROCEDURE: "nombre del procedimiento",
  },
  order: {
    NEW_ORDER: "Nueva orden",
    DISCOUNT: "Descuento ( $ )",
    SUBTOTAL: "SUBTOTAL",
    TOTAL: "TOTAL",
    NUMBER_SIMBOL: "#",
    ORDER_DESCRIPTION: "Producto/Servicio",
    UNIT_COST: "Costo Unitario",
    FROM_FILTER: "Desde",
    TO_FILTER: "Hasta",
    FILTER_BY_PATIENT: "BUSCAR ORDEN POR PACIENTE",
    FILTER_BY_DATE: "BUSCAR ORDEN POR FECHA",
    FILTER_BY_WAY_PAY: "FORMA DE PAGO",
    FILTER_BY_STATE: "ESTADO DE LA ORDEN",
    DATE_ORDER: "Fecha",
    NUMBER_ORDER: "# Orden",
    ORDER_PATIENT: "Paciente",
    ORDER_STATE: "Estado",
    PAY_WAY: "Forma de Pago",
    SUBTOTAL_TAX_12: "SubTotal 12%: $",
    SUBTOTAL_NO_TAX: "SubTotal 0%: $",
    SUBTOTAL_FOR_TAXES: "SubTotal: $",
    DISCOUNT_FOR_TAXES: "Descuentos: $",
    IVA: "IVA: $",
    TOTAL_FOR_TAXES: "TOTAL: $",
    PAYMENT: " Pago",
    VALUE: "Valor",
    DATE: "Fecha",
    SAVE_ORDER_PAYMENT: "Registrar pago",
    AMOUNT: "Monto de pago",
    DISABLED_ODER: "Esta orden no puede ser modificada.",
    INVOICE: "Factura",
    PAID_SUCCESS_ORDER: "Orden pagada satisfactoriamente",
    TAX12: "Impuesto ( IVA ) 12%",
  },
};

export const plurals = (text: string, cant: number) =>
  `${text}${cant === 1 ? "" : "s"}`;

export default STRINGS;
